### ISSUE TITLE
I get this error every time I open up the editor

### ISSUE THREAD

**Issue by CompuGeniusCode** [usagirei/3DS-Theme-Editor#16]
System.UnauthorizedAccessException: Access to the path './UserData' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at ThemeEditor.WPF.App.App_OnStartup(Object sender, StartupEventArgs e) in D:\GIT\Projects\3DS Theme Editor\ThemeEditor.WPF\App.xaml.cs:line 66
   at System.Windows.Application.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by CompuGeniusCode** [comment]
Ok, it's working now. I think it was because I was opening it from a search, as opposed to the actual folder.
