### ISSUE TITLE
Don't know what I screwed up, but apparently I did something

### ISSUE THREAD

**Issue by Platinuuum** [usagirei/3DS-Theme-Editor#17]
```System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at ThemeEditor.WPF.MainWindow.SendTheme_Execute(String ip, Boolean start) in D:\GIT\Projects\3DS Theme Editor\ThemeEditor.WPF\MainWindow.Themes.cs:line 0
   at ThemeEditor.WPF.MainWindow.SendTheme_Execute(String ip) in D:\GIT\Projects\3DS Theme Editor\ThemeEditor.WPF\MainWindow.Themes.cs:line 622
   at ThemeEditor.WPF.RelayCommandAsync`2.<Execute>d__11.MoveNext() in D:\GIT\Projects\3DS Theme Editor\ThemeEditor.WPF\RelayCommand.cs:line 226
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

**Comment by Platinuuum** [comment]
Lovely. Crashed and lost all of my work.
