### ISSUE TITLE
error when trying to load bgm

### ISSUE THREAD

**Issue by silly09** [usagirei/3DS-Theme-Editor#37]
im trying to make a theme and getting this error, how do i fix this?
it says to contact developer so i hope im doing this right
NAudio.MmException: InvalidParameter calling waveOutOpen
   at NAudio.Wave.WaveOut.Init(IWaveProvider waveProvider)
   at ThemeEditor.WPF.AudioPlayer.SetAudioData(Byte[] wavData) in D:\GIT\Projects\3DS Theme Editor\ThemeEditor.WPF\AudioPlayer.cs:line 81
   at ThemeEditor.WPF.MainWindow.LoadBGM_PostExecute(LoadBGMResults result) in D:\GIT\Projects\3DS Theme Editor\ThemeEditor.WPF\MainWindow.BGM.cs:line 17
   at ThemeEditor.WPF.RelayCommandAsync`1.<Execute>d__11.MoveNext() in D:\GIT\Projects\3DS Theme Editor\ThemeEditor.WPF\RelayCommand.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler

**Comment by idontwantanaccount69** [comment]
I'm having this same error when importing a bin file for a theme made with Kame-editor which I know for a fact does not have any pre-existing audio problems. (I'm importing my theme into Usagi to potentially fix a fade in/out music bug with Kame themes)

**Comment by skelebratz** [comment]
I'm having the same issue, but it corrupted the music before the errors started.
