### ISSUE TITLE
Application crashes on Windows 10 When loading a theme

### ISSUE THREAD

**Issue by astronautlevel2** [usagirei/3DS-Theme-Editor#4]
Stacktrace:

> NAudio.MmException: BadDeviceId calling waveOutOpen
>    at NAudio.Wave.WaveOut.Init(IWaveProvider waveProvider)
>    at ThemeEditor.WPF.AudioPlayer.SetAudioData(Byte[] wavData) in W:\Projects\3DS Theme Editor\ThemeEditor.WPF\AudioPlayer.cs:line 78
>    at ThemeEditor.WPF.MainWindow.LoadBGM_PostExecute(LoadBGMResults result) in W:\Projects\3DS Theme Editor\ThemeEditor.WPF\MainWindow.Themes.cs:line 112
>    at ThemeEditor.WPF.RelayCommandAsync`1.<Execute>d__11.MoveNext() in W:\Projects\3DS Theme Editor\ThemeEditor.WPF\RelayCommand.cs:line 0
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

I'm attempting to load a body_LZ.bin using the latest build.

**Comment by astronautlevel2** [comment]
Nevermind, my speaker was unplugged and .NET couldn't handle the exception
