### ISSUE TITLE
Crashes right after i try to run it.

### ISSUE THREAD

**Issue by CBetch37** [usagirei/3DS-Theme-Editor#7]
It said to "Contact the developer with the information below".
System.IO.FileFormatException: The image format is unrecognized. ---> System.Runtime.InteropServices.COMException: Exception from HRESULT: 0x88982F07
   --- End of inner exception stack trace ---
   at System.Windows.Media.PixelFormat.GetPixelFormat(SafeMILHandle bitmapSource)
   at System.Windows.Media.Imaging.BitmapSource.UpdateCachedSettings()
   at System.Windows.Media.Imaging.BitmapSource.set_WicSourceHandle(BitmapSourceSafeMILHandle value)
   at System.Windows.Media.Imaging.BitmapFrameDecode.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapSource.CompleteDelayedCreation()
   at System.Windows.Media.Imaging.BitmapSource.get_DpiX()
   at System.Windows.Media.Imaging.BitmapSource.GetWidthInternal()
   at System.Windows.Media.Imaging.BitmapSource.get_Width()
   at ThemeEditor.WPF.Markup.IconExtension.<ProvideValue>b__10_0(BitmapFrame f) in W:\Projects\3DS Theme Editor\ThemeEditor.WPF\Markup\IconExtension.cs:line 42
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ThemeEditor.WPF.Markup.IconExtension.ProvideValue(IServiceProvider serviceProvider) in W:\Projects\3DS Theme Editor\ThemeEditor.WPF\Markup\IconExtension.cs:line 42
   at ThemeEditor.WPF.MainWindow.LoadTheme_PostExecute(LoadThemeResults result) in W:\Projects\3DS Theme Editor\ThemeEditor.WPF\MainWindow.Themes.cs:line 188
   at ThemeEditor.WPF.RelayCommandAsync`1.<Execute>d__11.MoveNext() in W:\Projects\3DS Theme Editor\ThemeEditor.WPF\RelayCommand.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by usagirei** [comment]
Happens when you open the editor, or load a theme?
Also which Operating System?

**Comment by annchristinmijatovic** [comment]
Hi,

I think that I have a similar issue. I start the program and after about 2 to 3 minutes it says that Usagi 3DS Theme Editor doesn't work right and is going to be closed. 

I downloaded the zip file and always open ThemeEditor.WPF.exe. 
I'm using Windows 10.

Thanks in advance :)
